#!/usr/bin/env python3
import collections as cl

import src.val_tree.libs.http as http
import src.val_tree.libs.util as util


TREE_API    = 'https://ocenovanidrevin.nature.cz/hodnota-stromu.php'
TREE_OFFSET = {
    "abies sp."                                     : 267,
    "abies alba"                                    : 269,
    "abies alba 'pendula'"                          : 270,
    "abies alba 'pyramidalis'"                      : 271,
    "abies balsamea"                                : 268,
    "abies cephalonica"                             : 279,
    "abies concolor"                                : 278,
    "abies firma"                                   : 283,
    "abies grandis"                                 : 277,
    "abies holophylla"                              : 272,
    "abies homolepis"                               : 275,
    "abies koreana"                                 : 274,
    "abies lasiocarpa"                              : 281,
    "abies nordmanniana"                            : 273,
    "abies numidica"                                : 276,
    "abies pinsapo"                                 : 282,
    "abies procera"                                 : 285,
    "abies sibirica"                                : 280,
    "abies veitchii"                                : 284,
    "acer sp."                                      : 216,
    "acer campestre"                                : 217,
    "acer campestre 'elsrijk'"                      : 218,
    "acer campestre 'nanum'"                        : 219,
    "acer campestre 'postelense'"                   : 220,
    "acer campestre 'pulverulentum'"                : 221,
    "acer campestre 'queen elizabeth'"              : 222,
    "acer campestre 'red shine'"                    : 223,
    "acer campestre 'royal ruby'"                   : 224,
    "acer cappadocicum"                             : 238,
    "acer cappadocicum 'aureum'"                    : 239,
    "acer monspessulanum"                           : 231,
    "acer negundo"                                  : 232,
    "acer negundo 'aureo- variegatum'"              : 233,
    "acer negundo 'aureo-marginatum'"               : 234,
    "acer negundo 'flamingo'"                       : 235,
    "acer negundo 'odessanum'"                      : 236,
    "acer negundo 'variegatum'"                     : 237,
    "acer platanoides"                              : 248,
    "acer platanoides 'cleveland'"                  : 249,
    "acer platanoides 'columnare'"                  : 250,
    "acer platanoides 'crimson king'"               : 251,
    "acer platanoides 'crimson sentry'"             : 252,
    "acer platanoides 'deborah'"                    : 253,
    "acer platanoides 'drummondii'"                 : 254,
    "acer platanoides 'emerald queen'"              : 255,
    "acer platanoides 'faassen's black'"            : 256,
    "acer platanoides 'globosum'"                   : 257,
    "acer platanoides 'olmsted'"                    : 258,
    "acer platanoides 'palmatifidum'"               : 259,
    "acer platanoides 'royal red'"                  : 260,
    "acer platanoides 'schwedleri'"                 : 261,
    "acer platanoides 'summershade'"                : 262,
    "acer pseudoplatanus"                           : 240,
    "acer pseudoplatanus 'atropurpureum'"           : 241,
    "acer pseudoplatanus 'brilliantissimum'"        : 242,
    "acer pseudoplatanus 'erectum'"                 : 243,
    "acer pseudoplatanus 'leopoldii'"               : 244,
    "acer pseudoplatanus 'negenia'"                 : 245,
    "acer pseudoplatanus 'rotterdam'"               : 246,
    "acer pseudoplatanus 'worley'"                  : 247,
    "acer rubrum"                                   : 226,
    "acer rubrum 'armstrong'"                       : 227,
    "acer rubrum 'october glory'"                   : 228,
    "acer rubrum 'red sunset'"                      : 229,
    "acer rubrum 'scanlon'"                         : 230,
    "acer saccharinum"                              : 263,
    "acer saccharinum 'asplenifolium'"              : 264,
    "acer saccharinum 'laciniatum wieri'"           : 265,
    "acer saccharinum 'pyramidale'"                 : 266,
    "acer saccharum"                                : 225,
    "aesculus sp."                                  : 329,
    "aesculus flava"                                : 338,
    "aesculus hippocastanum"                        : 332,
    "aesculus hippocastanum 'baumannii'"            : 333,
    "aesculus hippocastanum 'fastigiata'"           : 334,
    "aesculus hippocastanum 'laciniata'"            : 335,
    "aesculus hippocastanum 'pyramidalis'"          : 336,
    "aesculus pavia"                                : 337,
    "aesculus x carnea"                             : 330,
    "aesculus x carnea 'briotii'"                   : 331,
    "ailanthus sp."                                 : 422,
    "ailanthus altissima"                           : 423,
    "alnus sp."                                     : 403,
    "alnus cordata"                                 : 409,
    "alnus glutinosa"                               : 404,
    "alnus glutinosa 'aurea'"                       : 405,
    "alnus glutinosa 'imperialis'"                  : 406,
    "alnus glutinosa 'laciniata'"                   : 407,
    "alnus incana"                                  : 410,
    "alnus incana 'aurea'"                          : 411,
    "alnus incana 'laciniata'"                      : 412,
    "alnus incana 'pendula'"                        : 413,
    "alnus x spaethii"                              : 408,
    "betula sp."                                    : 40,
    "betula alleghaniensis"                         : 57,
    "betula ermanii"                                : 49,
    "betula jacquemontii"                           : 50,
    "betula lenta"                                  : 56,
    "betula maximowicziana"                         : 51,
    "betula nigra"                                  : 48,
    "betula obscura"                                : 55,
    "betula oycoviensis"                            : 52,
    "betula papyrifera"                             : 53,
    "betula pendula"                                : 41,
    "betula pendula 'dalecarlica'"                  : 42,
    "betula pendula 'fastigiata'"                   : 43,
    "betula pendula 'laciniata'"                    : 44,
    "betula pendula 'purpurea'"                     : 45,
    "betula pendula 'tristis'"                      : 46,
    "betula pendula 'youngii'"                      : 47,
    "betula pubescens"                              : 54,
    "calocedrus sp."                                : 429,
    "calocedrus decurrens"                          : 430,
    "calocedrus decurrens 'aureovariegata'"         : 431,
    "carpinus sp."                                  : 161,
    "carpinus betulus"                              : 162,
    "carpinus betulus 'columnaris'"                 : 163,
    "carpinus betulus 'fastigiata'"                 : 164,
    "carpinus betulus 'frans fontaine'"             : 165,
    "carpinus betulus 'pendula'"                    : 166,
    "carpinus betulus 'purpurea'"                   : 167,
    "carpinus betulus 'quercifolia'"                : 168,
    "carya ovata"                                   : 414,
    "castanea sativa"                               : 339,
    "catalpa"                                       : 340,
    "catalpa bignonioides"                          : 343,
    "catalpa bignonioides 'nana'"                   : 344,
    "catalpa ovata"                                 : 345,
    "catalpa speciosa"                              : 342,
    "catalpa x erubescens"                          : 341,
    "cedrus sp."                                    : 87,
    "cedrus atlantica"                              : 88,
    "cedrus atlantica 'pendula'"                    : 89,
    "cedrus deodara"                                : 90,
    "cedrus libani"                                 : 91,
    "cedrus libani 'glauca'"                        : 92,
    "cedrus libani 'pendula'"                       : 93,
    "celtis sp."                                    : 37,
    "celtis australis"                              : 38,
    "celtis occidentalis"                           : 39,
    "cephalotaxus harringtonia"                     : 170,
    "cercidiphyllum sp."                            : 595,
    "cercidiphyllum japonicum"                      : 596,
    "cercidiphyllum japonicum 'pendulum'"           : 597,
    "corylus colurna"                               : 376,
    "corylus avellana"                              : 376,
    "crataegus sp."                                 : 171,
    "crataegus laevigata"                           : 173,
    "crataegus laevigata 'paul´s scarlet'"          : 174,
    "crataegus laevigata 'rubra plena'"             : 175,
    "crataegus monogyna"                            : 172,
    "cryptomeria sp."                               : 347,
    "cryptomeria japonica"                          : 348,
    "cryptomeria japonica 'araucarioides'"          : 349,
    "cryptomeria japonica 'cristata'"               : 350,
    "cunninghamia lanceolata"                       : 421,
    "davidia involucrata"                           : 127,
    "elaeagnus angustifolia"                        : 176,
    "fagus sp."                                     : 58,
    "fagus sylvatica"                               : 59,
    "fagus sylvatica 'ansorgei'"                    : 60,
    "fagus sylvatica 'aspleniifolia'"               : 61,
    "fagus sylvatica 'atropunicea'"                 : 62,
    "fagus sylvatica 'cochleata'"                   : 63,
    "fagus sylvatica 'cristata'"                    : 64,
    "fagus sylvatica 'dawyck gold'"                 : 65,
    "fagus sylvatica 'dawyck purple'"               : 66,
    "fagus sylvatica 'dawyck'"                      : 67,
    "fagus sylvatica 'laciniata'"                   : 68,
    "fagus sylvatica 'luteovariegata'"              : 69,
    "fagus sylvatica 'miltonensis'"                 : 70,
    "fagus sylvatica 'pendula'"                     : 71,
    "fagus sylvatica 'purple fountain'"             : 72,
    "fagus sylvatica 'purpurea nana'"               : 73,
    "fagus sylvatica 'purpurea pendula'"            : 74,
    "fagus sylvatica 'purpurea tricolor'"           : 75,
    "fagus sylvatica 'quercifolia'"                 : 76,
    "fagus sylvatica 'riversii'"                    : 77,
    "fagus sylvatica 'rohan gold'"                  : 78,
    "fagus sylvatica 'rohan obelisk'"               : 79,
    "fagus sylvatica 'rohanii'"                     : 80,
    "fagus sylvatica 'rotundifolia'"                : 81,
    "fagus sylvatica 'spaethiana'"                  : 82,
    "fagus sylvatica 'swat magret'"                 : 83,
    "fagus sylvatica 'tortuosa'"                    : 84,
    "fagus sylvatica 'tricolor'"                    : 85,
    "fagus sylvatica 'zlatia'"                      : 86,
    "fraxinus sp."                                  : 195,
    "fraxinus americana"                            : 196,
    "fraxinus angustifolia"                         : 200,
    "fraxinus angustifolia 'raywood'"               : 201,
    "fraxinus excelsior"                            : 202,
    "fraxinus excelsior 'allgold'"                  : 203,
    "fraxinus excelsior 'altena'"                   : 204,
    "fraxinus excelsior 'atlas'"                    : 205,
    "fraxinus excelsior 'aurea pendula'"            : 206,
    "fraxinus excelsior 'aurea'"                    : 207,
    "fraxinus excelsior 'crispa'"                   : 208,
    "fraxinus excelsior 'diversifolia'"             : 209,
    "fraxinus excelsior 'globosa'"                  : 210,
    "fraxinus excelsior 'heterophylla pendula'"     : 211,
    "fraxinus excelsior 'jaspidea'"                 : 212,
    "fraxinus excelsior 'nana'"                     : 213,
    "fraxinus excelsior 'pendula'"                  : 214,
    "fraxinus excelsior 'westhofs glorie'"          : 215,
    "fraxinus ornus"                                : 197,
    "fraxinus pennsylvanica"                        : 198,
    "fraxinus pennsylvanica 'aucubifolia'"          : 199,
    "ginkgo biloba"                                 : 323,
    "ginkgo biloba 'autumn gold'"                   : 324,
    "ginkgo biloba 'fastigiata'"                    : 325,
    "ginkgo biloba 'horizontalis'"                  : 326,
    "ginkgo biloba 'marieken'"                      : 327,
    "ginkgo biloba 'pendula'"                       : 328,
    "gleditsia sp."                                 : 132,
    "gleditsia triacanthos"                         : 133,
    "gleditsia triacanthos 'bujoti'"                : 134,
    "gleditsia triacanthos 'elegantissima'"         : 135,
    "gleditsia triacanthos 'shademaster'"           : 136,
    "gleditsia triacanthos 'skyline'"               : 137,
    "gleditsia triacanthos 'sunburst'"              : 138,
    "gleditsia triacanthos f. inermis"              : 139,
    "gymnocladus dioicus"                           : 402,
    "chamaecyparis sp."                             : 94,
    "chamaecyparis lawsoniana"                      : 102,
    "chamaecyparis lawsoniana 'alumii'"             : 103,
    "chamaecyparis lawsoniana 'columnaris'"         : 104,
    "chamaecyparis lawsoniana 'erecta viridis'"     : 105,
    "chamaecyparis lawsoniana 'filifera'"           : 106,
    "chamaecyparis lawsoniana 'fletcheri'"          : 107,
    "chamaecyparis lawsoniana 'glauca'"             : 108,
    "chamaecyparis lawsoniana 'golden wonder'"      : 109,
    "chamaecyparis lawsoniana 'ivonne'"             : 110,
    "chamaecyparis lawsoniana 'lane'"               : 111,
    "chamaecyparis lawsoniana 'lombartsii'"         : 112,
    "chamaecyparis lawsoniana 'lutescens'"          : 113,
    "chamaecyparis lawsoniana 'plumosa'"            : 114,
    "chamaecyparis lawsoniana 'silver queen'"       : 115,
    "chamaecyparis lawsoniana 'spek'"               : 116,
    "chamaecyparis lawsoniana 'stardust'"           : 117,
    "chamaecyparis lawsoniana 'stewartii'"          : 118,
    "chamaecyparis lawsoniana 'triomf van boskoop'" : 119,
    "chamaecyparis lawsoniana 'wisselii'"           : 120,
    "chamaecyparis nootkatensis"                    : 121,
    "chamaecyparis nootkatensis 'glauca'"           : 122,
    "chamaecyparis nootkatensis 'pendula'"          : 123,
    "chamaecyparis obtusa"                          : 124,
    "chamaecyparis pisifera"                        : 95,
    "chamaecyparis pisifera 'boulevard'"            : 96,
    "chamaecyparis pisifera 'filifera aurea'"       : 97,
    "chamaecyparis pisifera 'filifera'"             : 98,
    "chamaecyparis pisifera 'plumosa aurea'"        : 99,
    "chamaecyparis pisifera 'plumosa'"              : 100,
    "chamaecyparis pisifera 'squarrosa'"            : 101,
    "chamaecyparis thyoides"                        : 125,
    "juglans sp."                                   : 415,
    "juglans ailanthifolia"                         : 419,
    "juglans cinerea"                               : 418,
    "juglans mandshurica"                           : 417,
    "juglans nigra"                                 : 416,
    "juglans regia"                                 : 420,
    "juniperus sp."                                 : 188,
    "juniperus communis"                            : 189,
    "juniperus scopulorum"                          : 190,
    "juniperus scopulorum 'skyrocket'"              : 191,
    "juniperus virginiana"                          : 192,
    "juniperus virginiana 'glauca'"                 : 193,
    "juniperus virginiana 'kosteri'"                : 194,
    "koelreuteria paniculata"                       : 504,
    "koelreuteria paniculata 'fastigiata'"          : 505,
    "koelreuteria sp."                              : 503,
    "larix sp."                                     : 386,
    "larix decidua"                                 : 393,
    "larix decidua 'pendula'"                       : 394,
    "larix gmelini"                                 : 388,
    "larix kaempferi"                               : 389,
    "larix kaempferi 'blue rabbit'"                 : 390,
    "larix kaempferi 'diana'"                       : 391,
    "larix kaempferi 'pendula'"                     : 392,
    "larix laricina"                                : 387,
    "larix occidentalis"                            : 396,
    "larix sibirica"                                : 395,
    "liquidambar sp."                               : 0,
    "liquidambar styraciflua"                       : 1,
    "liriodendron"                                  : 351,
    "liriodendron tulipifera"                       : 352,
    "liriodendron tulipifera 'aureomarginatum'"     : 353,
    "liriodendron tulipifera 'fastigiatum'"         : 354,
    "maclura pomifera"                              : 436,
    "magnolia sp."                                  : 377,
    "magnolia acuminata"                            : 380,
    "magnolia hypoleuca"                            : 379,
    "magnolia kobus"                                : 378,
    "malus sp."                                     : 183,
    "malus domestica"                               : 184,
    "malus spectabilis"                             : 186,
    "malus sylvestris"                              : 185,
    "malus x zumi"                                  : 187,
    "metasequoia glyptostroboides"                  : 385,
    "morus sp."                                     : 398,
    "morus alba"                                    : 399,
    "morus alba 'pendula'"                          : 400,
    "morus nigra"                                   : 397,
    "ostrya carpinifolia"                           : 169,
    "padus sp."                                     : 497,
    "padus avium"                                   : 498,
    "padus avium 'albertii'"                        : 499,
    "parrotia persica"                              : 427,
    "paulownia tomentosa"                           : 428,
    "phellodendron amurense"                        : 346,
    "picea sp."                                     : 449,
    "picea abies"                                   : 484,
    "picea abies 'argenteospica'"                   : 485,
    "picea abies 'aurea magnifica'"                 : 486,
    "picea abies 'aurea'"                           : 487,
    "picea abies 'cincinnata'"                      : 488,
    "picea abies 'columnaris'"                      : 489,
    "picea abies 'cranstonii'"                      : 490,
    "picea abies 'cupressina'"                      : 491,
    "picea abies 'inversa'"                         : 492,
    "picea abies 'pendula major'"                   : 493,
    "picea abies 'rothenhaus'"                      : 494,
    "picea abies 'viminalis'"                       : 495,
    "picea abies 'virgata'"                         : 496,
    "picea alcoquiana"                              : 456,
    "picea asperata"                                : 455,
    "picea breweriana"                              : 451,
    "picea engelmannii"                             : 457,
    "picea glauca"                                  : 477,
    "picea jezoensis"                               : 450,
    "picea likiangensis"                            : 459,
    "picea mariana"                                 : 452,
    "picea mariana 'beissneri'"                     : 453,
    "picea omorika"                                 : 460,
    "picea omorika 'pendula'"                       : 461,
    "picea orientalis"                              : 478,
    "picea orientalis 'atrovirens'"                 : 479,
    "picea orientalis 'aurea'"                      : 480,
    "picea orientalis 'aureospica'"                 : 481,
    "picea orientalis 'gracilis'"                   : 482,
    "picea pungens"                                 : 462,
    "picea pungens 'edith'"                         : 463,
    "picea pungens 'endtz'"                         : 464,
    "picea pungens 'erich frahm'"                   : 465,
    "picea pungens 'fat albert'"                    : 466,
    "picea pungens 'fürst bismarck'"                : 467,
    "picea pungens 'glauca'"                        : 468,
    "picea pungens 'hoopsii'"                       : 469,
    "picea pungens 'koster'"                        : 470,
    "picea pungens 'moerheim'"                      : 471,
    "picea pungens 'montgomery'"                    : 472,
    "picea pungens 'oldenburg'"                     : 473,
    "picea pungens 'spek'"                          : 474,
    "picea rubens"                                  : 454,
    "picea schrenkiana"                             : 475,
    "picea sitchensis"                              : 476,
    "picea torano"                                  : 458,
    "picea wilsonii"                                : 483,
    "pinus sp."                                     : 2,
    "pinus aristata"                                : 22,
    "pinus banksiana"                               : 3,
    "pinus bungeana"                                : 6,
    "pinus cembra"                                  : 19,
    "pinus contorta"                                : 23,
    "pinus densiflora"                              : 13,
    "pinus flexilis"                                : 20,
    "pinus flexilis 'temple'"                       : 21,
    "pinus jeffreyi"                                : 14,
    "pinus koraiensis"                              : 15,
    "pinus leucodermis"                             : 4,
    "pinus nigra"                                   : 7,
    "pinus parviflora"                              : 8,
    "pinus parviflora 'glauca'"                     : 9,
    "pinus parviflora 'negishi'"                    : 10,
    "pinus parviflora 'tempelhof'"                  : 11,
    "pinus peuce"                                   : 25,
    "pinus ponderosa"                               : 27,
    "pinus pumila"                                  : 34,
    "pinus rigida"                                  : 29,
    "pinus rotundata"                               : 5,
    "pinus strobus"                                 : 30,
    "pinus strobus 'contorta'"                      : 31,
    "pinus strobus 'fastigiata'"                    : 32,
    "pinus strobus 'pendula'"                       : 33,
    "pinus sylvestris"                              : 16,
    "pinus sylvestris 'aurea'"                      : 17,
    "pinus sylvestris 'fastigiata'"                 : 18,
    "pinus thunbergii"                              : 28,
    "pinus uncinata"                                : 24,
    "pinus wallichiana"                             : 12,
    "pinus x schwerinii"                            : 26,
    "platanus sp."                                  : 432,
    "platanus occidentalis"                         : 435,
    "platanus orientalis"                           : 434,
    "platanus x hispanica"                          : 433,
    "populus sp."                                   : 516,
    "populus alba"                                  : 519,
    "populus alba 'nivea'"                          : 520,
    "populus alba 'pyramidalis'"                    : 521,
    "populus balsamifera"                           : 517,
    "populus lasiocarpa"                            : 525,
    "populus nigra"                                 : 522,
    "populus nigra 'italica'"                       : 523,
    "populus simonii"                               : 530,
    "populus simonii 'fastigiata'"                  : 531,
    "populus simonii 'pendula'"                     : 532,
    "populus tremula"                               : 527,
    "populus tremula 'erecta'"                      : 528,
    "populus tremula 'pendula'"                     : 529,
    "populus trichocarpa"                           : 524,
    "populus x berolinensis"                        : 518,
    "populus x canadensis"                          : 526,
    "populus x canescens"                           : 533,
    "prunus sp."                                    : 35,
    "prunus spinosa"                                : 35,
    "prunus sp."                                    : 383,
    "prunus sp."                                    : 437,
    "prunus sp."                                    : 445,
    "prunus sp."                                    : 546,
    "prunus sp."                                    : 551,
    "prunus armeniaca"                              : 384,
    "prunus avium"                                  : 548,
    "prunus avium 'plena'"                          : 549,
    "prunus cerasifera"                             : 401,
    "prunus cerasus"                                : 560,
    "prunus domestica"                              : 446,
    "prunus domestica ssp. insititia"               : 448,
    "prunus hillieri 'spire'"                       : 547,
    "prunus kurilensis 'brillant'"                  : 447,
    "prunus mahaleb"                                : 381,
    "prunus padus 'colorata'"                       : 500,
    "prunus persica"                                : 36,
    "prunus sargentii"                              : 561,
    "prunus sargentii 'rancho'"                     : 562,
    "prunus serotina"                               : 501,
    "prunus serrula"                                : 550,
    "prunus serrulata"                              : 438,
    "prunus serrulata 'amanogawa'"                  : 439,
    "prunus serrulata 'kanzan'"                     : 440,
    "prunus serrulata 'kiku-shidare-sakura'"        : 441,
    "prunus serrulata 'ukon'"                       : 442,
    "prunus subhirtella"                            : 552,
    "prunus subhirtella 'autumnalis rosea'"         : 553,
    "prunus subhirtella 'autumnalis'"               : 554,
    "prunus subhirtella 'fukubana'"                 : 555,
    "prunus subhirtella 'pendula plena rosea'"      : 556,
    "prunus virginiana"                             : 502,
    "prunus x amygdalo-persica"                     : 382,
    "prunus x yedoensis"                            : 557,
    "prunus x yedoensis 'ivensii'"                  : 558,
    "prunus x yedoensis 'shidare yoshino'"          : 559,
    "pseudolarix amabilis"                          : 425,
    "pseudotsuga sp."                               : 128,
    "pseudostsuga menziesii"                        : 129,
    "pseudotsuga menziesii"                         : 129,
    "pseudotsuga menziesii 'glauca pendula'"        : 130,
    "pseudotsuga menziesii var. glauca"             : 131,
    "pterocarya fraxinifolia"                       : 426,
    "pyrus sp."                                     : 177,
    "pyrus calleryana 'chanticleer'"                : 178,
    "pyrus calleryana 'redspire'"                   : 179,
    "pyrus communis"                                : 180,
    "pyrus communis 'beech hill'"                   : 181,
    "pyrus pyraster"                                : 182,
    "quercus sp."                                   : 140,
    "quercus alba"                                  : 142,
    "quercus cerris"                                : 144,
    "quercus coccinea"                              : 155,
    "quercus dalechampii"                           : 160,
    "quercus frainetto"                             : 157,
    "quercus imbricaria"                            : 143,
    "quercus macranthera"                           : 158,
    "quercus palustris"                             : 141,
    "quercus pedunculiflora"                        : 154,
    "quercus petraea"                               : 159,
    "quercus phellos"                               : 145,
    "quercus polycarpa"                             : 151,
    "quercus pubescens"                             : 152,
    "quercus robur"                                 : 148,
    "quercus robur 'fastigiata koster'"             : 149,
    "quercus robur 'fastigiata'"                    : 150,
    "quercus rubra"                                 : 146,
    "quercus virgiliana"                            : 147,
    "quercus x sargentii"                           : 153,
    "quercus x turneri 'pseudoturneri'"             : 156,
    "robinia sp."                                   : 536,
    "robinia luxurians"                             : 545,
    "robinia pseudoacacia"                          : 537,
    "robinia pseudoacacia 'bessoniana'"             : 538,
    "robinia pseudoacacia 'frisia'"                 : 539,
    "robinia pseudoacacia 'pyramidalis'"            : 540,
    "robinia pseudoacacia 'semperflorens'"          : 541,
    "robinia pseudoacacia 'tortuosa'"               : 542,
    "robinia pseudoacacia 'umbraculifera'"          : 543,
    "robinia viscosa"                               : 544,
    "salix sp."                                     : 563,
    "salix alba"                                    : 565,
    "salix alba 'liempde'"                          : 566,
    "salix alba 'sericea'"                          : 567,
    "salix alba ssp. vitellina"                     : 568,
    "salix babylonica"                              : 564,
    "salix caprea"                                  : 570,
    "salix daphnoides"                              : 572,
    "salix fragilis"                                : 571,
    "salix matsudana 'tortuosa'"                    : 569,
    "salix udensis"                                 : 575,
    "salix x rubens"                                : 573,
    "salix x sepulcralis"                           : 574,
    "sciadopitys verticillata"                      : 424,
    "sequoiadendron giganteum"                      : 443,
    "sequoiadendron giganteum 'pendula'"            : 444,
    "sophora sp."                                   : 292,
    "sophora japonica"                              : 293,
    "sophora japonica 'pendula'"                    : 294,
    "sophora japonica 'regent'"                     : 295,
    "sorbus sp."                                    : 296,
    "sorbus aria"                                   : 298,
    "sorbus aria 'aurea'"                           : 299,
    "sorbus aria 'lutescens'"                       : 300,
    "sorbus aria 'magnifica'"                       : 301,
    "sorbus aria 'majestica'"                       : 302,
    "sorbus aucuparia"                              : 305,
    "sorbus aucuparia 'edulis'"                     : 306,
    "sorbus aucuparia 'fastigiata'"                 : 307,
    "sorbus aucuparia 'pendula'"                    : 308,
    "sorbus aucuparia 'rossica major'"              : 309,
    "sorbus aucuparia 'sheerwater seedling'"        : 310,
    "sorbus domestica"                              : 303,
    "sorbus intermedia"                             : 304,
    "sorbus torminalis"                             : 297,
    "sorbus x hybrida"                              : 311,
    "taxodium sp."                                  : 509,
    "taxodium ascendens"                            : 515,
    "taxodium distichum"                            : 510,
    "taxodium distichum 'cascade falls'"            : 511,
    "taxodium distichum 'nutans'"                   : 512,
    "taxodium distichum 'pendens'"                  : 513,
    "taxodium distichum 'secrest'"                  : 514,
    "taxus sp."                                     : 506,
    "taxus baccata"                                 : 507,
    "taxus cuspidata"                               : 508,
    "thuja sp."                                     : 579,
    "thuja koraiensis"                              : 581,
    "thuja occidentalis"                            : 586,
    "thuja occidentalis 'alba'"                     : 587,
    "thuja occidentalis 'brabant'"                  : 588,
    "thuja occidentalis 'malonyana'"                : 589,
    "thuja occidentalis 'smaragd'"                  : 590,
    "thuja occidentalis 'spiralis'"                 : 591,
    "thuja occidentalis 'wareana'"                  : 592,
    "thuja orientalis"                              : 585,
    "thuja plicata"                                 : 582,
    "thuja plicata 'atrovirens'"                    : 583,
    "thuja plicata 'zebrina'"                       : 584,
    "thuja standishii"                              : 580,
    "thujopsis dolabrata"                           : 593,
    "thujopsis dolabrata 'variegata'"               : 594,
    "tilia sp."                                     : 355,
    "tilia americana"                               : 356,
    "tilia americana 'nova'"                        : 357,
    "tilia americana 'redmond'"                     : 358,
    "tilia cordata"                                 : 363,
    "tilia cordata 'green globe'"                   : 364,
    "tilia cordata 'greenspire'"                    : 365,
    "tilia cordata 'rancho'"                        : 366,
    "tilia cordata 'roelvo'"                        : 367,
    "tilia cordata 'winter orange'"                 : 368,
    "tilia petiolaris"                              : 362,
    "tilia platyphylos"                             : 371,
    "tilia platyphyllos"                            : 371,
    "tilia platyphyllos 'laciniata'"                : 372,
    "tilia platyphyllos 'örebro'"                   : 373,
    "tilia platyphyllos 'rubra'"                    : 374,
    "tilia tomentosa"                               : 369,
    "tilia tomentosa 'brabant'"                     : 370,
    "tilia x euchlora"                              : 375,
    "tilia x vulgaris"                              : 359,
    "tilia x vulgaris 'pallida'"                    : 360,
    "tilia x vulgaris 'zwarte linde'"               : 361,
    "torreya californica"                           : 534,
    "torreya nucifera"                              : 535,
    "tsuga sp."                                     : 286,
    "tsuga canadensis"                              : 288,
    "tsuga diversifolia"                            : 287,
    "tsuga heterophylla"                            : 290,
    "tsuga mertensiana"                             : 289,
    "tsuga sieboldii"                               : 291,
    "ulmus sp."                                     : 312,
    "ulmus glabra"                                  : 318,
    "ulmus glabra 'camperdownii'"                   : 319,
    "ulmus glabra 'exoniensis'"                     : 320,
    "ulmus glabra 'pendula'"                        : 321,
    "ulmus laevis"                                  : 322,
    "ulmus minor"                                   : 315,
    "ulmus minor 'dampieri aurea'"                  : 316,
    "ulmus parvifolia"                              : 313,
    "ulmus parvifolia 'geisha'"                     : 314,
    "ulmus x hollandica"                            : 317,
    "x cupressocyparis leylandii"                   : 126,
    "zelkova sp."                                   : 576,
    "zelkova carpinifolia"                          : 577,
    "zelkova serrata"                               : 578,
}

TREE_LOC_ATTR = {
    1: 'high',
    2: 'medium',
    3: 'less_significant',
    4: 'low',
    5: 'very_low',
}

TREE_GRW_COND = {
    1: 'unaffected',
    2: 'good',
    3: 'impaired',
    4: 'extreme',
}

ValuatedTree = cl.namedtuple('ValuatedTree', [
    'tree',
    'value_czk',
])
def make_tree_valuator(trees_per_sec):
    post = util.throttle(http.post, 1/trees_per_sec)
    def tree_valuator(aTree):
        response  = post(TREE_API, {
            'taxon'                  : f'{aTree.name_cz} ({aTree.name_lat})',
            'diameters'              : util.mapt(lambda x: max(5, x), aTree.diameters_cm),
            #^ The minimum diameter for a Tree to be valuated is 5cm
            'diameters_on_stumps'    : [],
            'height'                 : int(aTree.height_m),
            'stem_height'            : None,
            'spread'                 : None,
            'vitality'               : str(aTree.vitality),
            'health'                 : str(aTree.health),
            'removed_crown_volume'   : None,
            'location_attractiveness': TREE_LOC_ATTR[int(aTree.location_attractiveness)],
            'growth_conditions'      : TREE_GRW_COND[int(aTree.growth_conditions)],
            'microhabitats'          : [],
            'extensive_microhabitats': [],
            'taxon_offset'           : TREE_OFFSET[aTree.name_lat.lower()],
            '_taxon_cz'              : aTree.name_cz,
            '_taxon_lat'             : aTree.name_lat,
            'memorial_tree'          : False,
            'deliberately_planted'   : False
        })
        return ValuatedTree(tree = aTree, value_czk = response['value_in_czk'])
    return tree_valuator

